services:
    database:
        image: postgres
        container_name: postgres-brain-agriculture 
        restart: always
        shm_size: 128mb
        ports:
            - '5432:5432'
        volumes:
            - ./.docker/dbdata:/var/lib/postgresql/data
            - ./.docker/postgresql:/docker-entrypoint-initdb.d
        env_file:
            - .env

